import { createHmac, randomUUID } from 'node:crypto';
export type NucleusId = 'N01'|'N02'|'N03'|'N04'|'N05'|'N06'|'N07';
export type MeshKind = 'request'|'response'|'event'|'error';
export type SoulMeshMessage = { protocol:'soul-mesh/1'; contractVersion:'1.1.0'; id:string; correlationId:string; source:NucleusId; target:NucleusId; kind:MeshKind; capability:string; payload:unknown; timestamp:number; meta?:{runtime?:string;transport?:string;encoding?:string;version?:string;nonce?:string;traceId?:string} };
const PEERS: Exclude<NucleusId,'N01'>[]=['N02','N03','N04','N05','N06','N07'];
const env = (import.meta as ImportMeta & { env?: Record<string,string> }).env ?? {};
const urls:Partial<Record<NucleusId,string>>={N02:env.VITE_SOUL_MESH_N02_URL,N03:env.VITE_SOUL_MESH_N03_URL,N04:env.VITE_SOUL_MESH_N04_URL,N05:env.VITE_SOUL_MESH_N05_URL,N06:env.VITE_SOUL_MESH_N06_URL,N07:env.VITE_SOUL_MESH_N07_URL};
const secret=env.VITE_SOUL_MESH_HMAC_SECRET ?? '';
function uuid(){return globalThis.crypto?.randomUUID?.()??randomUUID();}
function nonce(){return uuid().replaceAll('-','').padEnd(32,'0').slice(0,32);}
function canonical(m:SoulMeshMessage, n:string){return JSON.stringify({protocol:m.protocol,contractVersion:m.contractVersion,id:m.id,correlationId:m.correlationId,source:m.source,target:m.target,kind:m.kind,capability:m.capability,payload:m.payload,timestamp:m.timestamp,meta:m.meta??null,nonce:n});}
function sign(m:SoulMeshMessage,n:string){return secret?createHmac('sha256',secret).update(canonical(m,n)).digest('hex'):'';}
export async function sendTo(target:NucleusId,capability:string,payload:unknown,timeoutMs=15000):Promise<SoulMeshMessage>{if(target==='N01')throw new Error('N01 inbound transport is owned by the Android runtime bridge');const url=urls[target];if(!url)throw new Error(`SOUL_MESH_PEER_URL_NOT_CONFIGURED:${target}`);if(!capability.trim())throw new Error('SOUL_MESH_CAPABILITY_REQUIRED');const correlationId=uuid();const message:SoulMeshMessage={protocol:'soul-mesh/1',contractVersion:'1.1.0',id:uuid(),correlationId,source:'N01',target,kind:'request',capability,payload,timestamp:Date.now(),meta:{runtime:'aeternum-core-29',transport:'HTTP',encoding:'json',version:'1.1.0',traceId:correlationId}};const n=nonce();message.meta={...(message.meta??{}),nonce:n};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const headers:Record<string,string>={'content-type':'application/json','x-soul-correlation-id':correlationId};if(secret)headers['x-soul-mesh-hmac']=sign(message,n);const response=await fetch(`${url.replace(/\/$/,'')}/api/soul-mesh`,{method:'POST',headers,body:JSON.stringify(message),signal:controller.signal});const body=await response.json() as SoulMeshMessage;if(body.correlationId!==correlationId)throw new Error('SOUL_MESH_CORRELATION_MISMATCH');if(body.contractVersion!=='1.1.0'||body.protocol!=='soul-mesh/1')throw new Error('SOUL_MESH_CONTRACT_MISMATCH');if(body.source!==target||body.target!=='N01')throw new Error('SOUL_MESH_ROUTE_MISMATCH');if(!response.ok||body.kind==='error')throw new Error(`SOUL_MESH_REMOTE_ERROR:${target}:${body.payload&&typeof body.payload==='object'&&'code'in body.payload?String((body.payload as {code:string}).code):response.status}`);return body;}finally{clearTimeout(timer);}}
export async function pingAll(timeoutMs=5000){return Promise.all(PEERS.map(async target=>{try{const response=await sendTo(target,'mesh.ping',{from:'N01',channel:`N01.OUT.${target}`},timeoutMs);return{target,status:'CONNECTED' as const,response};}catch(error){return{target,status:'FAILED' as const,error:String(error)};}}));}
export const N01_OUT_CHANNELS=PEERS.map(target=>`N01.OUT.${target}`);export const N01_IN_CHANNELS=PEERS.map(source=>`N01.IN.${source}`);export const N01_LOGICAL_CHANNELS=[...N01_OUT_CHANNELS,...N01_IN_CHANNELS];
