/**
 * AETERNUM artifact affinity registry.
 * Host affinity is balanced placement across N01-N07 + SARA.
 * It is NOT a transfer of canonical execution authority.
 * L1-L5 functional artifacts: 48. L6 adds 9 functional + 1 support index = 58 affinity entries.
 * L7 adds 13 distributed integration/projection/provenance entries = 71 total affinity entries.
 * Balance target is as-even-as-possible: 8 or 9 entries per participant (spread <= 1).
 */
export const AETERNUM_ARTIFACT_PARTICIPANTS = ["N01","N02","N03","N04","N05","N06","N07","SARA"] as const;
export type AeternumArtifactParticipant = typeof AETERNUM_ARTIFACT_PARTICIPANTS[number];
const ARTIFACTS = [
  {
    "id": "L1.CodexModule",
    "lot": "L1",
    "name": "CodexModule",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/CodexModule.ts",
    "canonicalAuthority": "N06",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "semantic/codex",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L1.CognitiveCalibrationModule",
    "lot": "L1",
    "name": "CognitiveCalibrationModule",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/CognitiveCalibrationModule.ts",
    "canonicalAuthority": "N06",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "cognitive/calibration",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L1.CognitiveNucleusModule",
    "lot": "L1",
    "name": "CognitiveNucleusModule",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/CognitiveNucleusModule.ts",
    "canonicalAuthority": "N06",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "cognitive/nucleus",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L1.MetaConsciousnessModule",
    "lot": "L1",
    "name": "MetaConsciousnessModule",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/MetaConsciousnessModule.ts",
    "canonicalAuthority": "N06",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "meta-cognition",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L1.MetaConsciousnessUI",
    "lot": "L1",
    "name": "MetaConsciousnessUI",
    "host": "N04",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/MetaConsciousnessUI.tsx",
    "canonicalAuthority": "N06",
    "kind": "ui",
    "canonicalAffinity": "M4_MIND",
    "domain": "cognitive/presentation",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L1.RealityCheckModule",
    "lot": "L1",
    "name": "RealityCheckModule",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/RealityCheckModule.ts",
    "canonicalAuthority": "N06",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "reasoning/reality-check",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L1.ScientificReasoningModule",
    "lot": "L1",
    "name": "ScientificReasoningModule",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/ScientificReasoningModule.ts",
    "canonicalAuthority": "N06",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "reasoning/scientific",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L1.SystemicGroundingModule",
    "lot": "L1",
    "name": "SystemicGroundingModule",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/SystemicGroundingModule.ts",
    "canonicalAuthority": "N06",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "reasoning/grounding",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L1.TemporalConsciousnessModule",
    "lot": "L1",
    "name": "TemporalConsciousnessModule",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/consciousness/TemporalConsciousnessModule.ts",
    "canonicalAuthority": "N06",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "cognitive/temporal",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.AudioRecordModule",
    "lot": "L2",
    "name": "AudioRecordModule",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/AudioRecordModule.ts",
    "canonicalAuthority": "N03",
    "kind": "engine",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "perception/audio",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.BNCv2MonitorModule",
    "lot": "L2",
    "name": "BNCv2MonitorModule",
    "host": "SARA",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/BNCv2MonitorModule.ts",
    "canonicalAuthority": "N03",
    "kind": "monitor",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "monitor/bnc",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.DCRSMonitorModule",
    "lot": "L2",
    "name": "DCRSMonitorModule",
    "host": "SARA",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/DCRSMonitorModule.ts",
    "canonicalAuthority": "N03",
    "kind": "monitor",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "monitor/dcrs",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.DIASPerformanceModule",
    "lot": "L2",
    "name": "DIASPerformanceModule",
    "host": "N01",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/DIASPerformanceModule.ts",
    "canonicalAuthority": "N03",
    "kind": "monitor",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "monitor/performance",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.FusionProcessModule",
    "lot": "L2",
    "name": "FusionProcessModule",
    "host": "N02",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/FusionProcessModule.ts",
    "canonicalAuthority": "N03",
    "kind": "engine",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "perception/fusion",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.MultimodalInputModule",
    "lot": "L2",
    "name": "MultimodalInputModule",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/MultimodalInputModule.ts",
    "canonicalAuthority": "N03",
    "kind": "engine",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "perception/multimodal",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.PerceptionModule",
    "lot": "L2",
    "name": "PerceptionModule",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/PerceptionModule.ts",
    "canonicalAuthority": "N03",
    "kind": "engine",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "perception/core",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.PerceptionUI",
    "lot": "L2",
    "name": "PerceptionUI",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/PerceptionUI.tsx",
    "canonicalAuthority": "N03",
    "kind": "ui",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "perception/ui",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L2.ProcessorDetailModule",
    "lot": "L2",
    "name": "ProcessorDetailModule",
    "host": "N02",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/modules/Perception/ProcessorDetailModule.ts",
    "canonicalAuthority": "N03",
    "kind": "engine",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "perception/processor",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.NeuralForgeModule",
    "lot": "L3",
    "name": "NeuralForgeModule",
    "host": "N07",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/evolution/NeuralForgeModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/forge",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.NeuralForgeUI",
    "lot": "L3",
    "name": "NeuralForgeUI",
    "host": "N04",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/evolution/NeuralForgeUI.tsx",
    "canonicalAuthority": "N07/SARA",
    "kind": "ui",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/forge-ui",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.SCRERefactorModule",
    "lot": "L3",
    "name": "SCRERefactorModule",
    "host": "N07",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/evolution/SCRERefactorModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/refactor",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.CodeGenesisModule",
    "lot": "L3",
    "name": "CodeGenesisModule",
    "host": "N07",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/evolution/CodeGenesisModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/codegen",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.BlueprintModule",
    "lot": "L3",
    "name": "BlueprintModule",
    "host": "N07",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/evolution/BlueprintModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/blueprint",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.ECASSynthesisModule",
    "lot": "L3",
    "name": "ECASSynthesisModule",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/evolution/ECASSynthesisModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/ecas",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.EvolutionCycleModule",
    "lot": "L3",
    "name": "EvolutionCycleModule",
    "host": "N07",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/evolution/EvolutionCycleModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/cycle",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.CSAModule",
    "lot": "L3",
    "name": "CSAModule",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/evolution/CSAModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/csa",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.ASCModule",
    "lot": "L3",
    "name": "ASCModule",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/evolution/ASCModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/asc",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L3.PalCoreAuditModule",
    "lot": "L3",
    "name": "PalCoreAuditModule",
    "host": "N07",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/aeternum/evolution/PalCoreAuditModule.ts",
    "canonicalAuthority": "N07/SARA",
    "kind": "engine",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "evolution/palcore-audit",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.VagusNerveServiceModule",
    "lot": "L4",
    "name": "VagusNerveServiceModule",
    "host": "N01",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/governance/VagusNerveServiceModule.ts",
    "canonicalAuthority": "N01",
    "kind": "service",
    "canonicalAffinity": "M1_CORE",
    "domain": "governance/vagus-service",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.VagusNerveReportModule",
    "lot": "L4",
    "name": "VagusNerveReportModule",
    "host": "N02",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/governance/VagusNerveReportModule.ts",
    "canonicalAuthority": "N01",
    "kind": "monitor",
    "canonicalAffinity": "M1_CORE",
    "domain": "governance/vagus-report",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.VagusNerveReportUI",
    "lot": "L4",
    "name": "VagusNerveReportUI",
    "host": "N02",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/governance/VagusNerveReportUI.tsx",
    "canonicalAuthority": "N01",
    "kind": "ui",
    "canonicalAffinity": "M1_CORE",
    "domain": "governance/vagus-ui",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.UnifiedCommandPipelineModule",
    "lot": "L4",
    "name": "UnifiedCommandPipelineModule",
    "host": "N01",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/governance/UnifiedCommandPipelineModule.ts",
    "canonicalAuthority": "N01",
    "kind": "engine",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "governance/command-pipeline",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.SystemIntegrationModule",
    "lot": "L4",
    "name": "SystemIntegrationModule",
    "host": "N01",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/governance/SystemIntegrationModule.ts",
    "canonicalAuthority": "N01",
    "kind": "service",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "governance/integration",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.ArchitectureGuideModule",
    "lot": "L4",
    "name": "ArchitectureGuideModule",
    "host": "N04",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/governance/ArchitectureGuideModule.ts",
    "canonicalAuthority": "N01",
    "kind": "guide",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "governance/architecture",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.MemoryModule",
    "lot": "L4",
    "name": "MemoryModule",
    "host": "SARA",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/governance/MemoryModule.ts",
    "canonicalAuthority": "SARA",
    "kind": "adapter",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "governance/memory",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.OrientationGuideModule",
    "lot": "L4",
    "name": "OrientationGuideModule",
    "host": "N04",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/governance/OrientationGuideModule.ts",
    "canonicalAuthority": "N06",
    "kind": "guide",
    "canonicalAffinity": "M4_MIND",
    "domain": "governance/orientation",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.GovernanceReportModule",
    "lot": "L4",
    "name": "GovernanceReportModule",
    "host": "SARA",
    "sourceRepo": "divibisoul/SARA",
    "sourcePath": "src/sara/meta/aeternum_governance_report.py",
    "canonicalAuthority": "SARA",
    "kind": "monitor",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "governance/report",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L4.EnforcementPipelineModule",
    "lot": "L4",
    "name": "EnforcementPipelineModule",
    "host": "SARA",
    "sourceRepo": "divibisoul/SARA",
    "sourcePath": "src/sara/meta/aeternum_enforcement_pipeline.py",
    "canonicalAuthority": "SARA",
    "kind": "service",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "governance/enforcement",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.UISystemsMonitorModule",
    "lot": "L5",
    "name": "UISystemsMonitorModule",
    "host": "N01",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "<new:lib/aeternum/monitors/UISystemsMonitorModule.ts>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/UISystemsMonitor.tsx",
    "canonicalAuthority": "N01/EventBus",
    "kind": "monitor",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "monitor/ui",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.UISystemsMonitorUI",
    "lot": "L5",
    "name": "UISystemsMonitorUI",
    "host": "N04",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "<new:src/aeternum/monitors/UISystemsMonitorUI.tsx>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/UISystemsMonitor.tsx",
    "canonicalAuthority": "N01/EventBus",
    "kind": "ui",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "monitor/ui-presentation",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.ActiveOperationsMonitorModule",
    "lot": "L5",
    "name": "ActiveOperationsMonitorModule",
    "host": "N01",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "<new:lib/aeternum/monitors/ActiveOperationsMonitorModule.ts>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/ActiveOperationsMonitor.tsx",
    "canonicalAuthority": "N01/EventBus",
    "kind": "monitor",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "monitor/operations",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.OperationStatusBarModule",
    "lot": "L5",
    "name": "OperationStatusBarModule",
    "host": "N02",
    "sourceRepo": "divibisoul/Eternium-",
    "sourcePath": "<new:src/aeternum/monitors/OperationStatusBarModule.ts>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/OperationStatusBar.tsx",
    "canonicalAuthority": "N02",
    "kind": "projection",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "monitor/operation-status",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.OperationProgressCardModule",
    "lot": "L5",
    "name": "OperationProgressCardModule",
    "host": "N02",
    "sourceRepo": "divibisoul/Eternium-",
    "sourcePath": "<new:src/aeternum/monitors/OperationProgressCardModule.ts>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/OperationProgressCard.tsx",
    "canonicalAuthority": "N02",
    "kind": "projection",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "monitor/operation-card",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.ExpertModeToggleModule",
    "lot": "L5",
    "name": "ExpertModeToggleModule",
    "host": "SARA",
    "sourceRepo": "divibisoul/SARA",
    "sourcePath": "<new:src/sara/meta/ExpertModeToggleModule.py>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/ExpertModeToggle.tsx",
    "canonicalAuthority": "SARA",
    "kind": "policy",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "governance/expert-mode",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.AgentCardModule",
    "lot": "L5",
    "name": "AgentCardModule",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "<new:src/aeternum/cards/AgentCardModule.ts>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/AgentCard.tsx",
    "canonicalAuthority": "N03",
    "kind": "projection",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "cards/agents",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.CapabilityCardModule",
    "lot": "L5",
    "name": "CapabilityCardModule",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "<new:src/aeternum/cards/CapabilityCardModule.ts>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/CapabilityCard.tsx",
    "canonicalAuthority": "N03",
    "kind": "projection",
    "canonicalAffinity": "M5_PERCEPTION",
    "domain": "cards/capabilities",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.CoreModuleCardModule",
    "lot": "L5",
    "name": "CoreModuleCardModule",
    "host": "N04",
    "sourceRepo": "divibisoul/nextjs-ai-chatbots",
    "sourcePath": "<new:src/aeternum/cards/CoreModuleCardModule.ts>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/CoreModuleCard.tsx",
    "canonicalAuthority": "N04",
    "kind": "projection",
    "canonicalAffinity": "M4_MIND",
    "domain": "cards/core-modules",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L5.SynthesisMetricsModule",
    "lot": "L5",
    "name": "SynthesisMetricsModule",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "<new:src/aeternum/monitors/SynthesisMetricsModule.ts>",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/SynthesisMetrics.tsx",
    "canonicalAuthority": "N06",
    "kind": "monitor",
    "canonicalAffinity": "M4_MIND",
    "domain": "monitor/synthesis",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.CommandProcessingModule",
    "lot": "L6",
    "name": "CommandProcessingModule",
    "host": "N01",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/system/CommandProcessingModule.ts",
    "canonicalAuthority": "N01/EventBus+HortaCore",
    "kind": "engine",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "system/command-processing",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.CommandProcessingUI",
    "lot": "L6",
    "name": "CommandProcessingUI",
    "host": "N04",
    "sourceRepo": "divibisoul/nextjs-ai-chatbots",
    "sourcePath": "src/aeternum/system/CommandProcessingUI.tsx",
    "canonicalAuthority": "N01/command-processing",
    "kind": "ui",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "system/command-processing-ui",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "<user-supplied CommandProcessingUI concept; no legacy file found>",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.ERUAuditModule",
    "lot": "L6",
    "name": "ERUAuditModule",
    "host": "SARA",
    "sourceRepo": "divibisoul/SARA",
    "sourcePath": "src/sara/meta/ERUAuditModule.py",
    "canonicalAuthority": "SARA/GovernanceBackend+DecisionTrace",
    "kind": "policy",
    "canonicalAffinity": "M7_EVOLUTION",
    "domain": "system/eru-audit",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.FullCognitionModule",
    "lot": "L6",
    "name": "FullCognitionModule",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/system/FullCognitionModule.ts",
    "canonicalAuthority": "N06Processor",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "system/full-cognition",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/FullCognitionModal.tsx",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.ModuleDetailModule",
    "lot": "L6",
    "name": "ModuleDetailModule",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/aeternum/system/ModuleDetailModule.ts",
    "canonicalAuthority": "N03AgentRegistry+SoulMeshCapabilityRegistry",
    "kind": "projection",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "system/module-detail",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "<user-supplied ModuleDetailModal concept; no legacy file found>",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.OmniModeModule",
    "lot": "L6",
    "name": "OmniModeModule",
    "host": "N07",
    "sourceRepo": "divibisoul/Orquestrador-",
    "sourcePath": "src/aeternum/system/OmniModeModule.ts",
    "canonicalAuthority": "N07/SARA orchestration boundary",
    "kind": "policy",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "system/omni-mode",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/OmniModeModal.tsx",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.QuantumCoreModule",
    "lot": "L6",
    "name": "QuantumCoreModule",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/system/QuantumCoreModule.ts",
    "canonicalAuthority": "N06Processor",
    "kind": "engine",
    "canonicalAffinity": "M4_MIND",
    "domain": "system/parallel-branch-compute",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "<user-supplied QuantumCoreModal concept; no legacy file found>",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.IconsModule",
    "lot": "L6",
    "name": "IconsModule",
    "host": "N02",
    "sourceRepo": "divibisoul/Eternium-",
    "sourcePath": "src/aeternum/system/IconsModule.ts",
    "canonicalAuthority": "N02 visual/component surface",
    "kind": "support",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "system/icons",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/icons.tsx",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.SynthesisLoaderModule",
    "lot": "L6",
    "name": "SynthesisLoaderModule",
    "host": "N04",
    "sourceRepo": "divibisoul/nextjs-ai-chatbots",
    "sourcePath": "src/aeternum/system/SynthesisLoaderModule.ts",
    "canonicalAuthority": "N04 presentation/runtime host",
    "kind": "projection",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "system/synthesis-loader",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/SynthesisLoader.tsx",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L6.SystemComponentsIndex",
    "lot": "L6",
    "name": "SystemComponentsIndex",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot",
    "sourcePath": "src/aeternum/system/index.ts",
    "canonicalAuthority": "Federated index only",
    "kind": "support",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "system/federation-index",
    "preservation": "existing source retained; host is federated surface affinity, not deletion or authority transfer",
    "federation": "SOUL_MESH / AETERNUM shared contracts; runtime reachability must be proven separately"
  },
  {
    "id": "L7.SystemPanelModule",
    "lot": "L7",
    "name": "SystemPanelModule",
    "host": "N01",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/panels/SystemPanelModule.ts",
    "canonicalAuthority": "N01/EventBus+HortaCore",
    "kind": "engine",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "panel/system-state",
    "preservation": "existing source retained; panel is an adapter and does not replace legacy UI",
    "federation": "SOUL_MESH / AETERNUM shared contracts; observed state only"
  },
  {
    "id": "L7.SystemPanelUI",
    "lot": "L7",
    "name": "SystemPanelUI",
    "host": "N02",
    "sourceRepo": "divibisoul/Eternium-",
    "sourcePath": "src/aeternum/panels/SystemPanelUI.tsx",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "components/SystemPanel.tsx",
    "canonicalAuthority": "N01/system-panel",
    "kind": "ui",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "panel/system-ui",
    "preservation": "legacy SystemPanel.tsx retained; new UI is a non-destructive projection",
    "federation": "SOUL_MESH / AETERNUM shared contracts; callbacks are explicit"
  },
  {
    "id": "L7.EngineeringPanelModule",
    "lot": "L7",
    "name": "EngineeringPanelModule",
    "host": "N04",
    "sourceRepo": "divibisoul/nextjs-ai-chatbots",
    "sourcePath": "src/aeternum/panels/EngineeringPanelModule.ts",
    "canonicalAuthority": "N04/Nucleus04Processor",
    "kind": "engine",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "panel/engineering-runtime",
    "preservation": "existing N04 processor remains sole capability execution authority",
    "federation": "SOUL_MESH / AETERNUM shared contracts; no local capability engine"
  },
  {
    "id": "L7.EngineeringPanelUI",
    "lot": "L7",
    "name": "EngineeringPanelUI",
    "host": "N02",
    "sourceRepo": "divibisoul/Eternium-",
    "sourcePath": "src/aeternum/panels/EngineeringPanelUI.tsx",
    "canonicalAuthority": "N04/engineering-panel",
    "kind": "ui",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "panel/engineering-ui",
    "preservation": "legacy architecture UI remains untouched",
    "federation": "SOUL_MESH / AETERNUM shared contracts; presentation only"
  },
  {
    "id": "L7.AuditPanelModule",
    "lot": "L7",
    "name": "AuditPanelModule",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/aeternum/audit/AuditPanelModule.ts",
    "canonicalAuthority": "Injected audit source; SARA remains governance authority",
    "kind": "projection",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "panel/audit-projection",
    "preservation": "no second governance engine; entries are explicit observations",
    "federation": "SOUL_MESH / AETERNUM shared contracts; source must be injected"
  },
  {
    "id": "L7.AuditPanelUI",
    "lot": "L7",
    "name": "AuditPanelUI",
    "host": "N03",
    "sourceRepo": "divibisoul/nexus-aeternum-fusion",
    "sourcePath": "src/aeternum/audit/AuditPanelUI.tsx",
    "canonicalAuthority": "N03/AuditPanelModule",
    "kind": "ui",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "panel/audit-ui",
    "preservation": "legacy audit UI remains untouched",
    "federation": "SOUL_MESH / AETERNUM shared contracts; presentation only"
  },
  {
    "id": "L7.ASASFPanelModule",
    "lot": "L7",
    "name": "ASASFPanelModule",
    "host": "SARA",
    "sourceRepo": "divibisoul/SARA",
    "sourcePath": "src/sara/meta/ASASFPanelModule.py",
    "canonicalAuthority": "SARA/GovernanceBackend+DecisionTrace",
    "kind": "policy",
    "canonicalAffinity": "M6_IMMUNITY",
    "domain": "panel/asasf-remediation",
    "preservation": "no synthetic remediation; execution requires injected real executor",
    "federation": "SARA governance + SOUL Mesh federation"
  },
  {
    "id": "L7.ASASFPanelUI",
    "lot": "L7",
    "name": "ASASFPanelUI",
    "host": "N06",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot-2000",
    "sourcePath": "src/aeternum/panels/ASASFPanelUI.tsx",
    "canonicalAuthority": "SARA/ASASFPanelModule",
    "kind": "ui",
    "canonicalAffinity": "M6_IMMUNITY",
    "domain": "panel/asasf-ui",
    "preservation": "presentation only; no remediation authority",
    "federation": "SOUL_MESH / AETERNUM shared contracts; state is supplied"
  },
  {
    "id": "L7.ChatEngineModule",
    "lot": "L7",
    "name": "ChatEngineModule",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot",
    "sourcePath": "src/aeternum/chat/ChatEngineModule.ts",
    "canonicalAuthority": "Injected N05 chat delegate",
    "kind": "engine",
    "canonicalAffinity": "M3_LANGUAGE",
    "domain": "panel/chat-engine",
    "preservation": "no synthetic response generation; default singleton is bound to canonical N05 inference, and explicit delegates remain supported",
    "federation": "SOUL_MESH / AETERNUM shared contracts; canonical N05 inference binding is explicit"
  },
  {
    "id": "L7.AppOrchestrator",
    "lot": "L7",
    "name": "AppOrchestrator",
    "host": "N01",
    "sourceRepo": "divibisoul/aeternum-core-29",
    "sourcePath": "lib/aeternum/orchestration/AppOrchestrator.ts",
    "canonicalAuthority": "N01/AeternumOrchestrator",
    "kind": "orchestrator",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "panel/app-orchestration",
    "preservation": "wraps the canonical orchestrator; does not create a second transport",
    "federation": "AETERNUM EventBus/HortaCore/Wormhole + SOUL Mesh"
  },
  {
    "id": "L7.GenesisModule",
    "lot": "L7",
    "name": "GenesisModule",
    "host": "N07",
    "sourceRepo": "divibisoul/Orquestrador-",
    "sourcePath": "src/aeternum/foundation/GenesisModule.ts",
    "canonicalAuthority": "Provenance metadata; no execution authority",
    "kind": "provenance",
    "canonicalAffinity": "M8_GOVERNANCE_MEMORY",
    "domain": "panel/genesis-provenance",
    "preservation": "user-supplied historical claims are marked as provenance, not execution evidence",
    "federation": "SOUL_MESH / AETERNUM shared contracts"
  },
  {
    "id": "L7.PanelsIndex",
    "lot": "L7",
    "name": "PanelsIndex",
    "host": "N07",
    "sourceRepo": "divibisoul/Orquestrador-",
    "sourcePath": "src/aeternum/foundation/panels-index.ts",
    "canonicalAuthority": "Federated index only",
    "kind": "support",
    "canonicalAffinity": "M2_ORCHESTRATION",
    "domain": "panel/federation-index",
    "preservation": "index contains descriptors only; no duplicate runtime",
    "federation": "SOUL_MESH / AETERNUM shared contracts"
  },
  {
    "id": "L7.AppIntegration",
    "lot": "L7",
    "name": "AppIntegration",
    "host": "N05",
    "sourceRepo": "divibisoul/nextjs-ai-chatbot",
    "sourcePath": "src/aeternum/integration/App.tsx",
    "legacySourceRepo": "divibisoul/Eternium-",
    "legacySourcePath": "App.tsx",
    "canonicalAuthority": "Host application remains canonical; adapter is additive",
    "kind": "integration",
    "canonicalAffinity": "M3_LANGUAGE",
    "domain": "panel/app-integration",
    "preservation": "root App.tsx was not replaced; integration boundary is additive",
    "federation": "AETERNUM/SOUL integration boundary; boot delegate is explicit"
  }
] as const;
export const AETERNUM_ARTIFACT_AFFINITY = ARTIFACTS;
export function getArtifactsByParticipant(participant: AeternumArtifactParticipant) { return ARTIFACTS.filter((artifact) => artifact.host === participant); }
export function getArtifact(id: string) { return ARTIFACTS.find((artifact) => artifact.id === id); }
export function getArtifactAffinityCounts() { return Object.fromEntries(AETERNUM_ARTIFACT_PARTICIPANTS.map((participant) => [participant, getArtifactsByParticipant(participant).length])); }
export function validateArtifactBalance() {
  const counts = getArtifactAffinityCounts() as Record<AeternumArtifactParticipant, number>;
  const errors: string[] = [];
  const values = AETERNUM_ARTIFACT_PARTICIPANTS.map((participant) => counts[participant]);
  const min = Math.min(...values);
  const max = Math.max(...values);
  for (const participant of AETERNUM_ARTIFACT_PARTICIPANTS) {
    if (counts[participant] < 8 || counts[participant] > 9) {
      errors.push(`BALANCE_RANGE_MISMATCH:${participant}:${counts[participant]}`);
    }
  }
  if (max - min > 1) errors.push(`BALANCE_SPREAD_EXCEEDED:${min}:${max}`);
  const ids = ARTIFACTS.map((artifact) => artifact.id);
  if (new Set(ids).size !== ids.length) errors.push("DUPLICATE_ARTIFACT_ID");
  return { ok: errors.length === 0, counts, errors, min, max };
}
