-- SOUL shared Supabase schema. Additive/idempotent migration; never drops existing data.
create extension if not exists vector;

create table if not exists public.contexts (
  id bigint generated by default as identity primary key,
  task_id text not null,
  correlation_id text not null,
  inputs jsonb not null default '{}'::jsonb,
  intermediate jsonb not null default '{}'::jsonb,
  final_result jsonb,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists contexts_task_id_idx on public.contexts(task_id);
create index if not exists contexts_correlation_id_idx on public.contexts(correlation_id);

create table if not exists public.audio_files (
  id bigint generated by default as identity primary key,
  cid text not null,
  task_id text,
  text text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audio_files_cid_idx on public.audio_files(cid);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  cid text not null,
  task_id text,
  content text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists documents_cid_idx on public.documents(cid);

create table if not exists public.embeddings (
  id bigint generated by default as identity primary key,
  task_id text,
  correlation_id text,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(768),
  created_at timestamptz not null default now()
);

create table if not exists public.soul_memories (
  id bigint generated by default as identity primary key,
  nucleus_id text not null,
  agent_id text,
  session_id text,
  content text not null,
  embedding vector(768) not null,
  memory_type text not null default 'episodic',
  metadata jsonb not null default '{}'::jsonb,
  importance double precision not null default 0.5,
  confidence double precision not null default 0.5,
  created_at timestamptz not null default now()
);
create index if not exists soul_memories_nucleus_idx on public.soul_memories(nucleus_id);
create index if not exists soul_memories_session_idx on public.soul_memories(session_id);

create or replace function public.match_soul_memories(
  query_embedding vector(768),
  match_threshold double precision,
  match_count integer,
  filter_nucleus_id text default null,
  filter_session_id text default null
)
returns table (
  id bigint,
  nucleus_id text,
  agent_id text,
  session_id text,
  content text,
  memory_type text,
  metadata jsonb,
  importance double precision,
  confidence double precision,
  similarity double precision,
  created_at timestamptz
)
language sql stable
as $$
  select
    m.id, m.nucleus_id, m.agent_id, m.session_id, m.content, m.memory_type,
    m.metadata, m.importance, m.confidence,
    1 - (m.embedding <=> query_embedding) as similarity,
    m.created_at
  from public.soul_memories m
  where 1 - (m.embedding <=> query_embedding) >= match_threshold
    and (filter_nucleus_id is null or m.nucleus_id = filter_nucleus_id)
    and (filter_session_id is null or m.session_id = filter_session_id)
  order by m.embedding <=> query_embedding
  limit greatest(1, least(match_count, 100));
$$;
